// src/features/users/components/UserSelect.vue
<template>
  <BaseCombobox
    :id="id"
    :label="label"
    :error="error"
    :placeholder="placeholder"
    :options="userOptions"
    v-model="modelValue"
    v-model:search="search"
  />
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import debounce from 'lodash-es/debounce'
import BaseCombobox from '@/shared/components/BaseCombobox.vue'
import { usersApi } from '@/features/users/api'

const props = defineProps<{
  id?: string
  label?: string
  error?: string
  placeholder?: string
  defaultSearch?: string
}>()

const modelValue = defineModel<string | number | undefined>()

const search = ref('')
const activeSearch = ref('')

onMounted(() => {
  if (props.defaultSearch) {
    search.value = props.defaultSearch
    activeSearch.value = props.defaultSearch
  }
})

const handleSearch = debounce(() => {
  activeSearch.value = search.value
}, 300)

watch(search, (newVal) => {
  handleSearch()
  if (!newVal) {
    modelValue.value = undefined
  }
})

const { data: usersData } = useQuery({
  queryKey: ['users', activeSearch],
  queryFn: () => usersApi.getUsers({ size: 5, search: activeSearch.value || undefined })
})

const userOptions = computed(() => {
  const options: { label: string, value: any }[] = []
  if (usersData.value?.data?.items) {
    usersData.value.data.items.forEach((u: any) => {
      options.push({ label: u.fullName || u.username, value: u.id })
    })
  }
  return options
})
</script>

// react-assessment/src/features/users/components/UserSelect.jsx
import { useState, useEffect } from 'react'
import { useQuery } from '@tanstack/react-query'
import BaseCombobox from '@/shared/components/BaseCombobox'
import { useDebounce } from '@/shared/hooks/useDebounce'
import { usersApi } from '@/features/users/api'

export default function UserSelect({
  id,
  label,
  error,
  placeholder,
  value,
  onValueChange,
  defaultSearch,
}) {
  const [searchText, setSearchText] = useState(defaultSearch || '')
  const activeSearch = useDebounce(searchText, 300)

  // Initialize searchText from defaultSearch on mount
  useEffect(() => {
    if (defaultSearch) {
      setSearchText(defaultSearch)
    }
  }, [defaultSearch])

  const { data: usersData } = useQuery({
    queryKey: ['users', activeSearch],
    queryFn: () => usersApi.getUsers({ size: 5, search: activeSearch || undefined }),
  })

  const options = (usersData?.data?.items || []).map((u) => ({
    label: u.fullName || u.username,
    value: u.id,
  }))

  function handleSearchChange(newSearch) {
    setSearchText(newSearch)
    if (!newSearch) {
      onValueChange?.(undefined)
    }
  }

  return (
    <BaseCombobox
      id={id}
      label={label}
      error={error}
      placeholder={placeholder}
      options={options}
      value={value}
      onValueChange={onValueChange}
      searchText={searchText}
      onSearchChange={handleSearchChange}
    />
  )
}
